version: '3.7'
services:
  app:
    image: tms-api-gw-node:latest
    container_name: tms-api-gw-node
    ports:
      - '5678:3000'
    volumes:
      - ./config:/usr/src/app/config
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    container_name: tms-api-gw-mongo
    ports:
      - '27017:27017'
    logging:
      driver: none
