version: '3.7'
services:
  jmongodb:
    build: ./mongodb
    image: api-gw/mongo:latest
    container_name: jh-mongo
  back:
    build: ./back
    image: api-gw/back:latest
    container_name: jh-back
