version: '3.7'
services:
  jmongodb:
    build: ./mongodb
    image: api-gw/mongo:latest
    container_name: jh-mongo
  back:
    build: ./back
    image: api-gw/back:latest
    container_name: jh-back
    #environment:
      #
      # - TMS_APP_PORT=6789
      # 转发规则 crm调it模块接口
      # - TMS_PROXY_RULES={"/interact-gateway/api/recv/orderBack_fk": "http://localhost:3730/it/api/recv/orderBack?domain=fk", "/interact-gateway/api/recv/orderBack_crm": "http://localhost:3730/it/api/recv/orderBack?domain=crm"}
      # mongo
      # - TMS_TRACE_MONGODB_USER=admin
      # - TMS_TRACE_MONGODB_PASSWORD=password
      # - TMS_TRACE_MONGODB_HOST=127.0.0.1
      # - TMS_TRACE_MONGODB_PORT=27018
      # - TMS_QUOTA_MONGODB_USER=admin
      # - TMS_QUOTA_MONGODB_PASSWORD=password
      # - TMS_QUOTA_MONGODB_HOST=127.0.0.1
      # - TMS_QUOTA_MONGODB_PORT=27018
      # 是否记录访问日志
      # - TMS_QUOTA_ENABLE=true
      # 是否记录转发日志
      # - TMS_TRACE_ENABLE=true
      # 是否鉴权
      # - TMS_TRACE_AUTH=true
      # 鉴权接口
      # - TMS_AUTH_HTTP_URL=http://localhost/oauth/ue/auth/authorize
      # - TMS_AUTH_HTTP_PATH=./lib/auth/auth.js

