version: '3.7'
services:
  jmongodb:
    build: ./mongodb
    image: 192.168.253.28/api-jh/mongo:latest
    container_name: jh-mongo
  back:
    build: ./back
    image: 192.168.253.28/api-jh/back:latest
    container_name: jh-back
